[package]
name = "dataset-3d-minecraft-generator"
version = "0.1.0"
author = "Nico Kandut"
edition = "2021"

[dependencies]
rand = "0.8.5"
vox-format = "0.1.0"
rayon = "1.8.0"
clap = { version = "4.4.11", features = ["derive"] }
